### ISSUE TITLE
Hello, I don't no which dataset should I download in coco2017 website, Can you give me a link to the exact dataset.

### ISSUE THREAD

**Issue by BJHYZJ** [POSTECH-CVLab/InstaOrder#1]
Hello, I don't no which dataset should I download in coco2017 website, Can you give me a link to the exact dataset.

**Comment by semonemo** [comment]
Hi, you need to download the following files:

[Images]
- 2017 Train images
- 2017 Val images

[Annotations]
- 2017 Train/Val annotations

**Comment by BJHYZJ** [comment]
Okay, Thank you.
